import { z } from 'zod';

export const ErrorCode = z.enum([
  'ORDER_NOT_FOUND',
  'PRODUCT_NOT_FOUND',
  'PRODUCT_UNAVAILABLE',
  'PRODUCT_INACTIVE',
  'TAX_PROFILE_INACTIVE',
  'INVALID_MODIFIER_SELECTION',
  'MODIFIER_UNAVAILABLE',
  'MODIFIER_INACTIVE',
  'ORDER_ALREADY_CLOSED',
  'ORDER_ALREADY_CANCELLED',
  'ORDER_ITEM_SENT',
  'ORDER_ITEM_NOT_FOUND',
  'ORDER_ITEM_PRODUCT_MISMATCH',
  'ORDER_ITEM_SPECIAL_INSTRUCTIONS_FROZEN',
  'SPECIAL_INSTRUCTIONS_TOO_LONG',
  'ORDER_BALANCE_NOT_ZERO',
  'ORDER_HAS_DRAFT_ITEMS',
  'ORDER_CURRENCY_MISMATCH',
  'ORDER_PAID_AMOUNT_EXCEEDS_TOTAL',
  'NO_DRAFT_ITEMS',
  'STALE_ORDER_VERSION',
  'DOMAIN_CONFLICT',
  'DOMAIN_ERROR',
  'PAYMENT_OVERPAYMENT',
  'INVALID_PAYMENT_AMOUNT',
  'INVALID_CASH_TENDERED',
  'PAYMENT_CURRENCY_MISMATCH',
  'PAYMENT_NOT_FOUND',
  'PAYMENT_NOT_COMPLETED',
  'CASH_SESSION_ALREADY_OPEN',
  'CASH_SESSION_NOT_OPEN',
  'INVALID_OPENING_FLOAT',
  'INVALID_BUSINESS_DATE',
  'TIPS_DISABLED',
  'INVALID_TIP',
  'COMMAND_ID_CONFLICT',
  'PRECHECK_REQUIRES_OPEN_ORDER',
  'RECEIPT_REQUIRES_CLOSED_ORDER',
  'VALIDATION_ERROR',
  'INVALID_REQUEST',
  'INTERNAL_ERROR',
]);

export type ErrorCode = z.infer<typeof ErrorCode>;

export const ErrorResponseSchema = z.object({
  error: ErrorCode,
  message: z.string(),
  details: z.any().optional(),
});

export type ErrorResponse = z.infer<typeof ErrorResponseSchema>;
